### Explanatory Data Analysis (EDA)

Imports

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Style

In [2]:
sns.set_theme(style="whitegrid")

Data

In [5]:
movies = pd.read_csv('../data/raw/movies.csv')
ratings = pd.read_csv('../data/raw/ratings.csv')
tags = pd.read_csv('../data/raw/tags.csv')
links = pd.read_csv('../data/raw/links.csv')

Data ingestion and preprocessing

In [9]:
display(movies.head(5))

,movieId,title,genres,release_year,title_clean
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0,Toy Story
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995.0,Jumanji
2,3,Grumpier Old Men (1995),Comedy|Romance,1995.0,Grumpier Old Men
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995.0,Waiting to Exhale
4,5,Father of the Bride Part II (1995),Comedy,1995.0,Father of the Bride Part II

In [8]:
movies['release_year'] = movies['title'].str.extract(r'\((\d{4})\)')
movies['release_year'] = pd.to_numeric(movies['release_year'], errors='coerce')
movies['title_clean'] = movies['title'].str.replace(r'\s*\(\d{4}\)', '', regex=True).str.strip()

In [10]:
ratings['datetime'] = pd.to_datetime(ratings['timestamp'], unit='s')
tags['datetime'] = pd.to_datetime(tags['timestamp'], unit='s')

In [11]:
ratings['rating_year'] = ratings['datetime'].dt.year
ratings['rating_month'] = ratings['datetime'].dt.month

In [12]:
df = ratings.merge(movies, on='movieId', how='left')

In [14]:
missing_data = df.isnull().sum()
print("\nMissing Values per Column:")
print(missing_data[missing_data > 0])

Missing Values per Column:
release_year    18
dtype: int64

In [16]:
duplicates = df.duplicated(subset=['userId', 'movieId']).sum()
print(f"\nDuplicates Found: {duplicates}")

Duplicates Found: 0

In [17]:
print("\nProcessed Master DataFrame Preview:")
display(df[['userId', 'title_clean', 'release_year', 'rating', 'datetime']].head())

Processed Master DataFrame Preview:

   userId           title_clean  release_year  rating            datetime
0       1             Toy Story        1995.0     4.0 2000-07-30 18:45:03
1       1      Grumpier Old Men        1995.0     4.0 2000-07-30 18:20:47
2       1                  Heat        1995.0     4.0 2000-07-30 18:37:04
3       1  Seven (a.k.a. Se7en)        1995.0     5.0 2000-07-30 19:03:35
4       1   Usual Suspects, The        1995.0     5.0 2000-07-30 18:48:51